version: '3.5'

services:
  app:
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    networks:
      - local_dev_network

  clickhouse:
    ports:
      - '8133:8123'
    volumes:
      - 'db:/data/clickhouse'
    networks:
      - local_dev_network

  mongodb:
    ports:
      - '27027:27017'
    volumes:
      - 'db:/data/mongodb'
    networks:
      - local_dev_network

networks:
  local_dev_network:
    driver: bridge

volumes:
  db:
    driver: local
