FROM node:18.13.0-alpine

RUN apk update && apk add --virtual --no-cache \
    git \
    openssh \
    ca-certificates \
    openjdk11-jre \
    zsh \
    curl \
    wget \
    procps \
    redis

RUN git clone https://github.com/powerline/fonts.git --depth=1
RUN sh fonts/install.sh
RUN rm -rf fonts

USER node

RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t https://github.com/romkatv/powerlevel10k \
    -p git \
    -p git-flow \
    -p https://github.com/zdharma-continuum/fast-syntax-highlighting \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions \
    -a 'export TERM=xterm-256color'

RUN echo '[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh' >> ~/.zshrc && \
    echo 'HISTFILE=/home/node/zsh/.zsh_history' >> ~/.zshrc

WORKDIR /app

RUN git config --global --add safe.directory /app
RUN yarn global add @nestjs/cli

CMD ["sh", "-c", "yarn install && yarn dev"]